Pygame dependency fix
NET-BYU/sss pull request #79
Opened 2024-11-01 02:56 UTC by apal6981

I was bothered that pygame was being imported by default. I changed that it only gets loaded when the screen is being simulated. The keyboard broadcaster was the culprit. I changed it that the keyboard is only checked when the virtual screen is being used. Also stuff from v2 merge so lets confirm and pull that one before this one.

2024-11-05 00:09 UTC, christopolise requested changes
Looks great for the most part, however when I run 

```bash
python3 main.py -vvv simulator 
```

I get an error saying that I needed to provide a value for `simulated`

```
Traceback (most recent call last):
  File "/home/christopolise/dev/sss/main.py", line 104, in <module>
    cli()
  File "/home/christopolise/dev/sss/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/christopolise/dev/sss/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/christopolise/dev/sss/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/christopolise/dev/sss/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/christopolise/dev/sss/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/christopolise/dev/sss/main.py", line 30, in run_simulator
    simulator.run()
  File "/home/christopolise/dev/sss/runners/simulator.py", line 366, in run
    sim.start()
  File "/home/christopolise/dev/sss/runners/simulator.py", line 310, in start
    handle_input = controllers.start_inputs(self.system_q, self.input_q)
TypeError: start_inputs() missing 1 required positional argument: 'simulated'
```

When checking the help messages, I find no mention of changes of command line args for running things in a simulated environment, so maybe include some of those if we are changing the way we run things?

2024-11-05 00:09 UTC, christopolise commented on controllers/__init__.py
>      """
If a new parameter is added, it should be updated in the docstring comment

2024-11-05 00:09 UTC, christopolise commented on demos/sweep/main.py
>              val (int): value of the line
Please update docstring param to match the signature of the function (i.e. val -> value)

2025-02-20 04:06 UTC, philipbl commented
@apal6981, can you rebase this PR so that the changes that were previously accepted don’t show up in this PR (physical_screen2.py, etc.)?

2025-02-25 00:49 UTC, apal6981 commented
I believe i have addressed the issues that needed to be addressed. I might have botched the rebase so somebody might want to look at that. I got a bit lost trying to do it on the commandline.

2025-11-14 23:27 UTC, merged